name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
      - main

  # run when a pull request is merged into master
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Create the dist directory
      - name: Create dist directory
        run: mkdir -p dist

      # generates a snake game from a GitHub user contributions graph, output a SVG animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: chas3air  # замените на ваше имя пользователя
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # Check the return of the previous step
      - name: Check if files were created
        run: |
          if [ -f dist/github-contribution-grid-snake.svg ]; then
            echo "File created: dist/github-contribution-grid-snake.svg"
          else
            echo "File not created: dist/github-contribution-grid-snake.svg"
          fi
          if [ -f dist/github-contribution-grid-snake-dark.svg ]; then
            echo "File created: dist/github-contribution-grid-snake-dark.svg"
          else
            echo "File not created: dist/github-contribution-grid-snake-dark.svg"
          fi

      # Check the contents of the dist directory
      - name: List files in dist directory
        run: ls -la dist

      # push the content of the dist directory to a branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist  # путь к папке dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}