name: Update Snake Animation

on:
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Snake Animations
      uses: Platane/snk/svg-only@v3
      with:
        github_user_name: ${{ github.chas3air }}
        outputs: |
          dist/github-contribution-grid-snake.svg
          dist/github-contribution-grid-snake-dark.svg
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

    - name: Save to dist folder
      run: |
        mkdir -p dist
        mv dist/*.* dist/
